### ISSUE TITLE
AttributeError: type object 'Trainer' has no attribute 'from_argparse_args'

### ISSUE THREAD

**Issue by beppe2hd** [lehaifeng/T-GCN#89]
Hi, I'm working on the PyTorch implementation of T-GCN.

Unfortunately the code fails in line 

`trainer = pl.Trainer.from_argparse_args(args, callbacks=callbacks)`

with the returned error:

`AttributeError: type object 'Trainer' has no attribute 'from_argparse_args'`

I'm currently working with pytorch_lightning 2.0.0

Unfortunately, losing around the documentation of pytorch_lightning I neither found any reference to the `from_argparse_args` method

Can someone suggest what I'm doing wrong?

**Comment by martinwhl** [comment]
`pl.Trainer.from_argparse_args()` method is deprecated in PL 2.x. Please consider downgrading your Lightning to 1.x (x >= 6) to run the current code, or switching to `LightningCLI` to solve this issue while using the latest version of Lightning.

**Comment by beppe2hd** [comment]
> `pl.Trainer.from_argparse_args()` method is deprecated in PL 2.x. Please consider downgrading your Lightning to 1.x (x >= 6) to run the current code, or switching to `LightningCLI` to solve this issue while using the latest version of Lightning.

Thanks. It worked perfectly
