### ISSUE TITLE
AttributeError: type object 'Trainer' has no attribute 'from_argparse_args'

### ISSUE THREAD

**Issue by beppe2hd** [lehaifeng/T-GCN#90]
Hi, I'm working on the PyTorch implementation of T-GCN.

Unfortunately the code fails in line

`trainer = pl.Trainer.from_argparse_args(args, callbacks=callbacks)`

with the returned error:

`AttributeError: type object 'Trainer' has no attribute 'from_argparse_args'
`
I'm currently working with pytorch_lightning 2.0.0

Unfortunately, losing around the documentation of pytorch_lightning I neither found any reference to the `from_argparse_args` method

Can someone suggest what I'm doing wrong?

**Comment by martinwhl** [comment]
Duplicate of #89.
